import type { Metadata } from "next";
import type { ReactElement, ReactNode } from "react";
import localFont from "next/font/local";

import "@/globals.css";

import RootProvider from "@/providers/root-provider";
import { hasSessionTokensAction } from "@/actions/session.actions";
import { LayoutWrapper } from "@/components/layout/layout-wrapper";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}): Promise<ReactElement> {
  const { locale } = await params;
  const { hasRefreshToken } = await hasSessionTokensAction();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <RootProvider session={hasRefreshToken} locale={locale}>
          <LayoutWrapper>{children}</LayoutWrapper>
        </RootProvider>
      </body>
    </html>
  );
}
