import type { Metadata } from "next";
import type { ReactElement, ReactNode } from "react";
import { Inter, Orbitron, Quantico } from "next/font/google";

import "@/globals.css";

import RootProvider from "@/providers/root-provider";
import { hasSessionTokensAction } from "@/actions/session.actions";
import { LayoutWrapper } from "@/components/layout/layout-wrapper";
import { cn } from "@/lib/utils";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const quantico = Quantico({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-quantico",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}): Promise<ReactElement> {
  const { locale } = await params;
  const { hasRefreshToken } = await hasSessionTokensAction();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("font-sans", orbitron.variable, inter.variable, quantico.variable)}>
        <RootProvider session={hasRefreshToken} locale={locale}>
          <LayoutWrapper>{children}</LayoutWrapper>
        </RootProvider>
      </body>
    </html>
  );
}
