export const API_PROCEDURE_ERRORS = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  FAILED_TO_LOGOUT: "FAILED_TO_LOGOUT",
  SESSION_EXPIRED_OR_INVALID: "SESSION_EXPIRED_OR_INVALID",
  SESSION_INVALID: "SESSION_INVALID",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  CONFLICT: "CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
} as const;
export type ApiProcedureErrors = (typeof API_PROCEDURE_ERRORS)[keyof typeof API_PROCEDURE_ERRORS];
