name: Mobile Preview (Expo)
on:
  push:
    branches: [main]
    paths:
      - "apps/mobile/**"
      - "packages/**"
  workflow_dispatch: # allows manual triggering of the workflow
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build dependencies
        run: pnpm turbo run build --filter=@repo/*
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Publish Update
        run: |
          cd apps/mobile
          CI=1 npx eas-cli update --branch preview --message "${{ github.event.head_commit.message || 'Manual update' }}"
